window.tyrano_lang = {
    word: {
        go_title: "Return to the title. Are you sure?",
        exit_game: "Close the window and exit. Are you sure?",
        not_saved: "There is no saved data yet.",
        confirm: "Confirm",
        confirm_beforeunload: "There are unsaved changes. Do you want to exit the game?",
        tag: "Tag",
        not_exists: "does not exist.",
        error: "An error occurred. Please check the script.",
        label: "Label",
        label_double: "is duplicated within the same scenario file.",
        error_occurred: "An error occurred.",
        save_file_violation_1: "Detected movement of save data. If the save data is not trusted, do not load it under any circumstances.",
        save_file_violation_2: "Do you want to load the save data and start the game?",
        save_file_violation_3: "Startup canceled. Delete the save data and try starting again.",
        double_start: "The game is already running. You cannot start it twice.",
        reload: "Reload",
        line: "line { line }",
        initialized_saved_data: "Initialized save data.",
        initializing_saved_data: "Initialize save data. Are you sure?",
        saved_data_is_corrupted: "Save data may be corrupted. Do you want to initialize the save data?",
        save_does_not_work: "Save functionality does not work in this environment. This can occur when running locally.",
        undefined_tag: "Tag「{ name }」does not exist.",
        undefined_label: "Label「{ name }」does not exist.",
        undefined_character: "The specified character「{ name }」is not defined. Define it with [chara_new].",
        undefined_face: "The expression「{ face }」for the specified character「{ name }」is not defined. Define it with [chara_face].",
        undefined_character_parts: "The variant parts for the specified character「{ name }」are not defined. Define them with [chara_layer].",
        undefined_keyframe: "The specified keyframe animation「{ keyframe }」is not defined. Define it with [keyframe].",
        undefined_3d_model: "The specified 3D model「{ name }」is not defined.",
        preload_failure_sound:
            "Audio file「{ src }」not found. Is the path specified as a full path?\n\n(Example) ./data/bgm/my_bgm.mp3",
        preload_failure_image:
            "Image file「{ src }」not found. Is the path specified as a full path?\n\n(Example) ./data/image/my_image.png",
        preload_failure_video:
            "Video file「{ src }」not found. Is the path specified as a full path?\n\n(Example) ./data/video/my_video.mp4",
        invalid_keyframe: "The keyframe has an invalid value.",
        invalid_keyframe_percentage:
            'The percentage「{ percentage }」set for the keyframe is invalid. Specify it like "0%" or "30%".',
        error_in_iscript: "An error occurred inside [iscript].",
        missing_endif: "After [if], one of [elsif] [else] [endif] was not found. Or there are too many tags inside [if].",
        missing_endmacro: "After [macro], [endmacro] was not found. Or there are too many tags inside [macro].",
        missing_endignore: "After [ignore], [endignore] was not found. Or there are too many items inside [ignore].",
        missing_parameter: "Parameter「{ param }」is required for tag「{ tag }」.",
        if_and_endif_do_not_match: "The number of [if] and [endif] do not match.",
        unsupported_extensions: "「{ ext }」is an unsupported file format.",
        undefined_keyconfig:
            'Key configuration is not defined. KeyConfig.js may be missing or there may be a syntax error in KeyConfig.js. Please check that commas "," or brackets "]" "}" are not missing.',
        compensate_missing_quart:
            'Detected an unexpected "]". The number of parameter quotes may be insufficient, so it will be automatically corrected and interpreted.\n\nBefore: { before }\nAfter: { after }',
        duplicate_label:
            "Label「{ name }」is duplicated within the same scenario file. Ensure label names are not duplicated within the same scenario file.",
        file_not_found: "File not found.\n\n{ path }",
        patch_not_found: "Patch file not found.\n\n{ path }",
        new_patch_found: "A new update was found.\n\nVer: { version }\n{ message }\n\n Do you want to apply the update?",
        apply_web_patch: "Applying the update. The game will automatically exit when complete.",
        apply_patch_complete: "Update applied. Please restart the game.",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
        error_occurred: "error occurred",
    },
};
